export const IMAGES = {
  splash: require('./Images/launch_screen.png'),

  //icon
  logo: require('./Icons/logo.png'),
  ar: require('./Icons/ar.png'),
  en: require('./Icons/en.png'),
  google: require('./Icons/google.png'),
  apple: require('./Icons/apple.png'),
  back: require('./Icons/back.png'),
  back1: require('./Icons/back1.png'),
  pick1: require('./Icons/pick1.png'),
  info: require('./Icons/info.png'),
  addnew: require('./Icons/addnew.png'),

  banner: require('./Icons/banner.png'),
  bg: require('./Icons/bg.png'),
  Burgers: require('./Icons/Burgers.png'),
  cardAdd: require('./Icons/cardAdd.png'),
  Delivery: require('./Icons/Delivery.png'),
  GroupMeals: require('./Icons/GroupMeals.png'),
  HouseParty: require('./Icons/HouseParty.png'),
  ic_Burgers: require('./Icons/ic_Burgers.png'),
  ic_Promotions: require('./Icons/ic_Promotions.png'),
  Individual_ic: require('./Icons/Individual_ic.png'),
  Individual: require('./Icons/Individual.png'),
  KidsMeal: require('./Icons/KidsMeal.png'),
  MenuCategories: require('./Icons/MenuCategories.png'),
  notification: require('./Icons/notification.png'),
  onNotifi: require('./Icons/onNotifi.png'),
  Pickup: require('./Icons/Pickup.png'),
  Platter: require('./Icons/Platter.png'),
  downIC: require('./Icons/downIC.png'),
  Promotions: require('./Icons/Promotions.png'),
  rightside: require('./Icons/rightside.png'),
  search: require('./Icons/search.png'),
  Sides: require('./Icons/Sides.png'),
  user: require('./Icons/user.png'),

  usetTab: require('./Icons/usetTab.png'),
  list: require('./Icons/list.png'),
  home: require('./Icons/home.png'),
  addCart: require('./Icons/addCart.png'),
  line: require('./Icons/line.png'),
  bg1: require('./Icons/bg1.png'),
  checkIn: require('./Icons/checkIn.png'),
  checkOut: require('./Icons/checkOut.png'),
  bug: require('./Icons/bug.png'),
  location: require('./Icons/location.png'),
  pay: require('./Icons/pay.png'),
  plush: require('./Icons/plush.png'),
};
